/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cbd_nutribd;

import DB.DocDB;
import DB.GraphDB;
import DB.ImgDB;
import DB.RelationalDB;
import Data.CreateDocumentXML;
import Data.Prato;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Andreia Machado
 */
public class InsertDoc extends javax.swing.JFrame {
    private Prato plate;
    /**
     * Creates new form InsertDoc
     */
    public InsertDoc() {
        initComponents();
        this.setTitle("Inserir Prato");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PreparacaoTXT = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        CozinhaTXT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DoseTXT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TempoTXT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        DificuldadeTXT = new javax.swing.JTextField();
        AdicionarPrato = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Preparação");

        PreparacaoTXT.setColumns(20);
        PreparacaoTXT.setRows(5);
        jScrollPane1.setViewportView(PreparacaoTXT);

        jLabel3.setText("Tipo de Cozinha");

        jLabel4.setText("Doses");

        jLabel5.setText("Tempo");

        jLabel6.setText("Dificuldade");

        DificuldadeTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DificuldadeTXTActionPerformed(evt);
            }
        });

        AdicionarPrato.setText("Adicionar Prato");
        AdicionarPrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarPratoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AdicionarPrato)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CozinhaTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                                .addComponent(DoseTXT)
                                .addComponent(TempoTXT)
                                .addComponent(DificuldadeTXT)))
                        .addComponent(jLabel2)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CozinhaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(DoseTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TempoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(DificuldadeTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AdicionarPrato)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DificuldadeTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DificuldadeTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DificuldadeTXTActionPerformed

    private void AdicionarPratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarPratoActionPerformed
        GraphDB graph = new GraphDB();
        ImgDB imgBD = new ImgDB();
        boolean added = true;
        try {
            added = graph.addPratoGrafosDB(plate);
            added = imgBD.insertImage(plate.getImagem());
        } catch (SQLException | FileNotFoundException ex) {
            Logger.getLogger(InsertPlate.class.getName()).log(Level.SEVERE, null, ex);
        }
        RelationalDB relational = new RelationalDB();
        DocDB docBD = new DocDB();
        int id;
        try {
            id = relational.getIdPrato(plate);
            prepararDocumento(id);
            added = docBD.insertDoc("doc"+id);
        } catch (SQLException ex) {
            Logger.getLogger(InsertDoc.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (added)
            JOptionPane.showMessageDialog(this, "Prato criado com sucesso!");
        else
            JOptionPane.showMessageDialog(this, "O prato não for criado!");
        this.dispose();
    }//GEN-LAST:event_AdicionarPratoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertDoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdicionarPrato;
    private javax.swing.JTextField CozinhaTXT;
    private javax.swing.JTextField DificuldadeTXT;
    private javax.swing.JTextField DoseTXT;
    private javax.swing.JTextArea PreparacaoTXT;
    private javax.swing.JTextField TempoTXT;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void prepararDocumento(int id) {
        String nome = "doc"+id;
        String preparacao = PreparacaoTXT.getText();
        String cozinha = CozinhaTXT.getText();
        String dificuldade = DificuldadeTXT.getText();
        String tempo = TempoTXT.getText();
        String dose = DoseTXT.getText();
        CreateDocumentXML cdxml = new CreateDocumentXML(nome);
        try {
            cdxml.createDocument(id, preparacao, cozinha, dificuldade, tempo, dose);
        } catch (IOException ex) {
            Logger.getLogger(InsertDoc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void setPlate(Prato plate) {
        this.plate = plate;
    }
}
